USE ESTUDOS
GO

-- O USO DO APPLY EM GERAL
-- TANTO O CROSS APPLY QUANTO O OUTER APPLY REALIZAM "JOINS" CRUZADOS
-- CRUZADOS NÃO NO ANGULO DIAGONAL, E SIM DE QUE TODOS OS REGISTROS DA ESQUERDA DEVEM SE BATER COM OS DA DIREITA (CROSS)
-- OU QUE TODOS OS REGISTROS DA ESQUERDA DEVEM SER RETORNADOS, INCLUSIVE AQUELES QUE NÃO TEM COM QUEM BATER COM OS DA DIREITA (OUTER)
-- UMA DAS CARACTERÍSTICAS QUE ME CHAMOU A ATENÇÃO FOI A POSSIBILIDADE DE MANIPULAR LINHA A LINHA DOS REGISTROS RETORNADOS.
-- A POSSIBILIDADE DE DEIXAR A QUERY DE ENTRO DO APPLY MAI DINÂMICA TORNA A CONSULTA MAIS FLEXÍVEL PARA CONSULTAS MAIS ESPECÍFICAS
-- COMO POR EXEMPLO TRAZER N RESULTADOS DE CADA UM DOS TIPOS X DE PRODUTO EM APENAS 1 RESULTSET

-- EXEMPLO 1 : TRAZER TODOS OS TIPOS ACESSÓRIOS E O MODELO DOS RESPECTIVOS CARROS QUE OS USAM
SELECT
  ACESSORIO_TP_ACESSORIO [ID_TIPO],
  ACESSORIO_DS_DESCRICAO [DESCRICAO],
  CARRO_DS_MODELO [MODELO]
FROM ACESSORIO OUTER APPLY (SELECT CARRO_DS_MODELO FROM CARRO WHERE ACESSORIO_TP_ACESSORIO = CARRO_TP_ACESSORIO) O 

-- EXEMPLO 2 : TRAZER APENAS OS ACESSÓRIOS USADOS SE LIMITANDO A APENAS 1 VEICULO POR TIPO DE ACESSÓRIO E MODELO E ANO DO VEÍCULO
SELECT
  ACESSORIO_TP_ACESSORIO [ID_TIPO],
  ACESSORIO_DS_DESCRICAO [DESCRICAO],
  CARRO_DS_MODELO [MODELO],
  CARRO_NR_ANO [ANO]
FROM ACESSORIO CROSS APPLY (SELECT TOP 1 * FROM CARRO WHERE CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO) O