USE ESTUDOS
GO

-- CROSS APPLY
-- O CROSS APPLY TEM UM CONCEITO MUITO INTERESSANTE
-- É UM JOIN "CRUZADO", POR ASSIM DIZER
-- BASICAMENTE EU CONSIGO FAZER UMA ESPÉCIE DE SUBSELECT DENTRO DO DOS PARÂMETROS DO CROSS APPLY E EU FAÇO A JUNÇÃO ENTRE A TABELA DESCRITA
-- APÓS O FROM COM O QUE ESTÁ DENTRO DO CROSS APPLY.
-- NO CROSS APPLY É POSSÍVEL USAR UMA FUNÇÃO DE TABELA COMO PARTE DO FROM.

-- EXEMPLO 1 : CONTANDO A QUANTIDADE DE VEÍCULOS QUE USAM CADA UM DOS ACESSÓRIOS
-- ESSE EXEMPLO PODERIA SER FACILMENTE SUBSTITUIDO COM UM SELECT COM JOIN E FAZENDO UM GROUPBY E UM COUNT(*)
-- CONTUDO O APPLY ENTRA NESSE EXEMPLO MOSTRANDO QUE A QUERY CONTIDA DENTRO DO APPLY FOI EXECUTADA PARA CADA UMA DAS LINHAS!
SELECT 
  * 
FROM 
  ACESSORIO CROSS APPLY (SELECT
                           COUNT(*) [QNT]
                         FROM 
                           CARRO
                         WHERE 
                           CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO
                         ) AS O



-- EXEMPLO 2 : MOSTRANDO O ID DE CADA UM DOS CARROS Q UTILIZA OS ACESSÓRIOS
-- NESTE EXEMPLO CONSEGUIMOS VER CADA UMA DAS LINHAS DE ACESSÓRIO SENDO UNIDAS (JOIN) COM O RETORNO
-- DA QUERY DENTRO DO CROSS APPLY
-- PODERÍAMOS TER FEITO A MESMA COISA UTILIZANDO O INNER JOIN - CONTUDO A DIFERENÇA É NA QUERY PERSONALIZADA DENTRO DO APPLY!!!!!!!!!
-- REPARE QUE FOI FEITO UM TOP 2 O QUE FLEXIBILIZA A NOSSA QUERY
-- EXEMPLO: TRAGA NO MESMO RESULT SET APENAS 2 VEÍCULOS QUE UTILIZAM CADA UM DOS TIPOS DE ACESSÓRIOS.
-- ACESSÓRIO 1 (COMPLETO) SE UNIU A: AOS 2 VEÍCULOS DA TABELA CARRO QUE POSSUEM ACESSÓRIO IGUAL A 1
-- NESTE CASO CONSEGUIMOS MONTAR UMA RELAÇÃO DE 1XN
-- 1 REGISTRO DA TABELA DA ESQUERDA (ACESSÓRIO) PODE SE ASSOCIAR A N REGISTROS DA DIREITA (CARRO DENTRO DO APPLY).
SELECT 
  * 
FROM 
  ACESSORIO CROSS APPLY (SELECT TOP 2 
                           CARRO_NR_ID
                         FROM 
                           CARRO
                         WHERE 
                           CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO) AS O
