USE ESTUDOS
GO

-- OUTER APPLY
-- É BASICAMENTE UM LEFT JOIN
-- SEMPRE VAI FAVORECER A TABELA DA ESQUERDA (ACESSORIO), TRAZENDO TODOS OS REGISTROS DELA, MESMO QUE NÃO TENHAM COM QUEM ASSOCIAR.

-- EXEMPLO 1 : TRAZER TODOS OS ACESSÓRIOS E CONTAR A QUANTIDADE DE VEÍCULOS QUE USAM CADA UM DOS ACESSÓRIOS
SELECT 
  * 
FROM 
  ACESSORIO OUTER APPLY (SELECT
                           COUNT(*) [QNT]
                         FROM 
                           CARRO
                         WHERE 
                           CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO
                         ) AS O

-- EXEMPLO 2 : TRAZER TODOS OS ACESSÓRIOS E TRAZER O ID DOS 2 PRIMEIROS VEÍCULOS QUE USAM CADA UM DOS ACESSÓRIOS
SELECT 
  * 
FROM 
  ACESSORIO OUTER APPLY (SELECT TOP 2 
                           CARRO_NR_ID
                         FROM 
                           CARRO
                         WHERE 
                           CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO) AS O
