USE ESTUDOS
GO
-- AVALIAR O PLANO DE EXECUÇÃO CONTROL+L PARA EXECUTAR.
-- NESTE MOMENTO ESTOU ME BASENDO NO CUSTO DO LOTE DE CONSULTA
-- AO QUE PARECE, NESSE CASO A SUBQUERY É MAIS RÁPIDA QUE O JOIN POIS CUSTA MENOS (LEVANDO EM CONSIDERAÇÃO O CUSTO POR LOTE MENOR)

SELECT * FROM CARRO INNER JOIN ACESSORIO ON (CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO)
--SELECT * FROM CARRO, ACESSORIO WHERE CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO
SELECT * FROM CARRO WHERE CARRO_TP_ACESSORIO IN (SELECT ACESSORIO_TP_ACESSORIO FROM ACESSORIO)