CREATE PROCEDURE SP_VENDER(
  @ID_CARRO NUMERIC(18,0),
  @ID_COMPRADOR NUMERIC(18,0)
) AS 
BEGIN

WITH CTE_VEICULO_X_VENDA (ID_COMPRADOR, VALOR_TOTAL, DATA_VENDA, NR_VEICULO)AS (
SELECT
  @ID_COMPRADOR,
  CARRO_VL_FIPE - CARRO_VL_FIPE * (CARRO_PC_DSCAVISTA/100),
  CONVERT(VARCHAR(8), GETDATE(), 112),
  @ID_CARRO
FROM 
  CARRO 
WHERE 
  CARRO_NR_ID = @ID_CARRO  
)

  INSERT INTO VENDA SELECT * FROM CTE_VEICULO_X_VENDA

END

USE ESTUDOS
GO

-- USO DOS GROUPING SETS
-- SERVE PARA AGRUPAR UM CONJUNTO DE GRUPOS, BASICAMENTE

DECLARE @I NUMERIC(18,0) = 0
DECLARE @J NUMERIC(18,0) = 11

WHILE (@J <> 0)
BEGIN

EXECUTE SP_VENDER @ID_CARRO = @I, @ID_COMPRADOR = @J

SELECT @I = @I+1
SELECT @J = @J-1
END