-- BASICAMENTE CRUZA TODAS OS REGISTROS DAS DUAS TABELAS
-- A QUANTIDADE TOTAL DE REGISTROS DE RETORNO É A QUANTIDADE DE REGISTROS DA TABELA 1 X A QUANTIDADE DE REGISTROS DA TABELA 2
-- EM RESUMO, FAZ UM TODOS COM TODOS. (GERA TODAS AS POSSIBILIDADES).
SELECT 
  *
FROM
  CARRO CROSS JOIN ACESSORIO 