-- FULL OUTER JOIN E FULL JOIN SÃO A MESMA COISA. BASICAMENTE TRAZEM TODOS OS REGISTROS DE TODAS AS TABELAS ENVOLVIDAS.
-- LEFT OUTER JOIN É A MESMA COISA QUE LEFT JOIN
-- RIGHT OUTER JOIN É A EMSMA COISA QUE RIGHT JOIN
SELECT 
  CARRO_NR_ID, 
  CARRO_NR_ANO, 
  CARRO_DS_MODELO,
  ACESSORIO_DS_DESCRICAO
FROM
  CARRO FULL OUTER JOIN ACESSORIO ON (
    CARRO_TP_ACESSORIO = ACESSORIO_TP_ACESSORIO
)