-- FUN합ES DE VALORES DE TABELA
-- S홒 FUN합ES QUE PODEM SER USADAS EM COMANDOS FROM, JOIN, CROSS E OUTER APPLY
-- AS FUN합ES DE VALORES DE TABELA DEVOLVEM COMO RESULTSET UM CONJUNTO DE DADOS.

USE ESTUDOS

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE sysobjects.name='FNC_CALCDESCONTO')
  DROP FUNCTION FNC_CALCDESCONTO
GO
/*-------------------------*/
/* SCHEMA DE CONSTRU플O    */
/*-------------------------*//*

CREATE FUNCTION NOME_FUNCAO (
  @PARAMETRO DATATYPE
)
RETURNS DATATYPE DE RETORNO OU @TABELA DE RETORNO TABLE (
  CAMPO_TABELA DATATYPE
)
AS
BEGIN
  CORPO DA FUNCTION
  
  RETURN
END

/*-------------------------*/*/
/*                         */
/*-------------------------*/


/*-------------------------*/
/* CONSTRUINDO A FUN플O    */
/*-------------------------*/
CREATE FUNCTION FNC_CALCDESCONTO (
  @VL_VEICULO  NUMERIC(17,2),
  @PC_DESCONTO NUMERIC(5,2)
)
RETURNS @TB_DESCONTOCARRO TABLE (
  VALOR_DESCONTO NUMERIC(17,2),
  VALOR_FINAL    NUMERIC(17,2))
AS
BEGIN
  INSERT INTO @TB_DESCONTOCARRO
  SELECT
    @VL_VEICULO * (@PC_DESCONTO/100),
	@VL_VEICULO - (@VL_VEICULO * (@PC_DESCONTO/100))
  
  RETURN
END

GO

-- EXEMPLO 1: UTILIZANDO O RETORNO DA FUN플O DE VALOR DE TABELA PARA UTILIZAR NO FROM
SELECT * FROM dbo.FNC_CALCDESCONTO(17900.00, 5.00)