USE ESTUDOS
GO

-- O DENSE_RANK REALIZA UM "ORDENAMENTO" DOS VALORES.
-- É OBRIGATÓRIO PASSAR AS INFORMAÇÕES DO ORDER BY
-- A CLAUSULA PARTITION BY (DENTRO DO OVER) É UM OPCIONAL. ELA PODE REALIZAR A SEGMENTAÇÃO DO GRUPO POR MAIS UMA JANELA
-- VALORES EQUIVALENTES DO CAMPO COLOCADO COMO PARÂMETRO, NO NOSSO EXEMPLO CARRO_VL_FIPE, SERÃO CONSIDERADOS TENDO O MESMO ID
-- O VLR RANK SE REPETE PARA OS CAMPOS EQUIVALENTES INFORMADOS COMO PARÂMETRO PARA O OVER.


-- A UNICA DIFERENÇA ENTRE O DENSE_RANK E O RANK É QUE O DENSE RANK NÃO PULA A ORDEM DOS IDS! (PODE ATÉ REPETIR, MAS O PRÓXIMO ID É A SEQUENCIA DO ÚLTIMO).
SELECT
  DENSE_RANK() OVER (ORDER BY CARRO_VL_FIPE ASC) [VLR RANK],
  CARRO_VL_FIPE
FROM 
  CARRO