USE ESTUDOS
GO

-- SÃO CHAMADAS FUNÇÕES DE JANELA PORQUE RETORNAM OS RESULTADOS DE MANEIRA ORGANIZADA E POR QUADRANTES
/*
EXEMPLO GERAL:

NOTA ALUNO	TURMA	MÉDIA DE NOTAS DA TURMA
	10		  B				8
	5		  C				7.5
	6         B				8
	7         A				8
	10		  C				7.5
	9         A				8


O RESULTADO ACIMA DESCRITO SERIA RETORNADO DA SEGUINTE MANEIRA:

NOTA ALUNO	TURMA	MÉDIA DE NOTAS DA TURMA
	10		  B				8
	6         B				8
	----------------------------------
	7         A				8
	9         A				8
	----------------------------------
	5		  C				7.5
	10		  C				7.5

O QUE DEVE SER LEVADO EM CONSIDERAÇÃO, NÃO É A ORDEM DO RESULTSET, E SIM A FORMA COM A QUAL ELA FOI AGRUPADA EM UMA FORMA DE JANELA
REGISTROS DA TURMA B ESTÃO TODOS JUNTOS, ASSIM COMO DAS TURMAS A E C.
*/

-- AS WINDOWS FUNCTIONS / FUNÇÕES DE JANELAS AGREGADAS SÃO RELATIVAMENTE FACEIS DE USAR.
-- EU CONSIGO TRAZER UM VALOR AGREGADO POR CONTA DA FUNÇÃO AVG SEM UTILIZAR O GROUP BY
-- MOTIVO PELO QUAL DE FATO ELA NÃO AGRUPA OS RESULTADOS, E SIM O REPETE
-- ENTÃO PARA CADA REGISTRO DA TABELA CARRO -> A MÉDIA DE VALOR POR ACESSÓRIO SERÁ REPETIDA DE MANEIRA IGUAL. DIFERINDO APENAS SE O ACESSÓRIO FOR DIFERENTE.

-- EXEMPLO 1 : TRAGA O MODELO DO CARRO, A DESCRIÇÃO DOS ACESSÓRIOS E O VALOR MÉDIO DOS VEÍCULOS DO MESMO ACESSÓRIO.
SELECT 
  CARRO_DS_MODELO [MODELO CARRO],
  ACESSORIO_DS_DESCRICAO [ACESSORIOS],
  AVG(CARRO_VL_FIPE) OVER (PARTITION BY CARRO_TP_ACESSORIO)[MÉDIA DE VALOR POR ACESSÓRIO]
FROM 
  CARRO CROSS APPLY (
    SELECT 
	  ACESSORIO_DS_DESCRICAO 
	FROM 
	  ACESSORIO 
	WHERE 
	  ACESSORIO_TP_ACESSORIO = CARRO_TP_ACESSORIO
  ) AS ACESSORIO


-- O MESMO EXEMPLO SERVE PARA QUALQUER UMA DAS FUNÇÕES AGREGADAS!