USE ESTUDOS
GO

-- O COMANDO NTILE REALIZA UMA DIVISÃO DO RESULTSET
-- NTILE(PARAM1) OVER ([PARTITION BY PARAM2] ORDER BY PARAM3)
-- PARAM1 = QUANTIDADE DE GRUPOS QUE SERÃO CRIADOS (SUBDIVISÕES)
-- PARAM2 = ESTÁ JUNTO COM O PARTITINO, O QUAL NÃO É OBRIGATÓRIO, É A DIVISÃO POR DUPLAS / PARTICIONAMENTO A CONTAGEM VAI REINICIAR
-- PARAM3 = FORMA DE ORDENAÇÃO DA CONTAGEM DO NTILE

-- REALIZA UMA DIVISÃO TOTAL DOS VALORES DO RESULTSET DEPENDENDO DA QUANTIDADE ESPECIFICADA NO SEU PARÂMETRO

-- EXEMPLO 1 : TRAZ TODOS OS MODELOS DE VEÍCULOS E OS DIVIDE EM 2 GRUPOS (DE ACORDO COM A QUANTIDADE DE PORTAS)
SELECT 
  CARRO_DS_MODELO,
  NTILE(2) OVER(ORDER BY CARRO_QT_PORTAS ASC)
FROM
  CARRO