USE ESTUDOS
GO

-- O ROW_NUMBER() É MUITO PARECIDO COM O RANK, PORÉM ELA NÃO ESTIPULA O VALOR DO ITEM, E SIM REALIZA APENAS UMA CONTAGEM EM ORDEM
-- CADA ID É UNICO, INDEPENDENTE SE O VALOR DO CAPO SEJA O MESMO, O ID SERÁ DIFERENTE UM DO OUTRO.
-- SE ESPECÍFICADO A CLAUSULA PARTITION BY, DENTRO DO OVER, A NUMERAÇÃO VAI SER INICIADA NOVAMENTE DE ACORDO COM A TUPLA (EXEMPLO 2)

-- EXEMPLO 1 
SELECT
  ROW_NUMBER() OVER (ORDER BY CARRO_VL_FIPE ASC) [ID],
  CARRO_VL_FIPE
FROM
  CARRO

-- EXEMPLO 2
SELECT 
  ROW_NUMBER() OVER (PARTITION BY CARRO_TP_ACESSORIO ORDER BY CARRO_TP_ACESSORIO) [ID],
  CARRO_TP_ACESSORIO
FROM
  CARRO