USE ESTUDOS
GO

-- O PIVOT É RESPONSÁVEL POR TRANSFORMAR LINHAS EM COLUNAS!
-- SINTAXE:
/*

SELECT
  'INDICADOR DA COLUNA' AS ALIASDOCAMPO, [IDENTIFICADOR DO CAMPO QUE SE TORNARÁ UMA COLUNA]
FROM 
  (
    SELECT 
	  CAMPO_QUE_VAI_SER_AGREGADO, 
	  CAMPO_QUE_VAI_SE_TORNAR_COLUNA 
	FROM 
	  TABELA
  ) AS ALIAS_ORIGEM 
PIVOT (FNC_AGREGADA(CAMPO_QUE_VAI_SER_AGREGADO) FOR CAMPO_QUE_SERA_A_COLUNA) IN ([IDENTIFICADOR DO CAMPO QUE SE TORNARÁ UMA COLUNA]) AS TB_PIVOT

*/

-- NO EXEMPLO ABAIXO, QUEREMOS UMA LINHA QUE INDIQUE A SOMA DAS VENDAS DA DATA 20200915
-- DEVEMOS ESPECIFICAR NO PARÂMETRO DO IDENTIFICADOR A DATA ESPECÍFICA QUE QUEREMOS OS VALORES
SELECT 
  'Valor médio das vendas por data' AS Vlr_Medio_Vendas_Diario, [20200915]
FROM (SELECT VENDA_VL_TOTAL, VENDA_DT_VEND FROM VENDA) AS VENDAS PIVOT (SUM(VENDA_VL_TOTAL) FOR VENDA_DT_VEND IN ([20200915])) AS TB_PIVOT

-- LINKS DE AJUDA : https://stackoverflow.com/questions/63974618/sql-t-sql-pivot-return-null

-- EXEMPLO 2 : TRAZER O VALOR MÉDIO DOS VEÍCULOS PELOS TIPOS DE ACESSÓRIOS
-- PERCEBA QUE AS COLUNAS SÃO 1, 2, 3, 4 QUE RESPECTIVAMENTE SÃO OS TIPOS DE ACESSÓRIOS DO CAMPO CARRO_TP_ACESSORIO!
SELECT
  'Valor médio dos veículos por tipo de acessório' AS Vlr_Medio_Carros_Por_Acessorio, [1],[2],[3],[4]
FROM
  (
    SELECT
	  CARRO_VL_FIPE,
	  CARRO_TP_ACESSORIO
	FROM
	  CARRO
  ) AS CARRO
PIVOT (AVG(CARRO_VL_FIPE) FOR CARRO_TP_ACESSORIO IN ([1], [2], [3], [4])) AS TB_PIVOT