USE ESTUDOS
GO

-- UNPIVOT TRANSFORMA COLUNAS EM LINHAS
-- OS CAMPOS DA TABELA DERIVADA PRECISAM ESTAR NO MESMO DATA TYPE!
-- BASICAMENTE CONVERTE AS COLUNAS EM LINHAS


-- EXEMPLO 1 : CONVERTE OS CAMPOS DA TABELA ACESSORIO EM LINHAS, TRAZENDO OS RESULTADOS AO LADO DE MANEIRA HORIZONTAL.
SELECT
  [COLUNAS], [VALORES]
FROM
  (
    SELECT
	  CONVERT(VARCHAR(100), ACESSORIO_TP_ACESSORIO) [ACESSORIO_TP_ACESSORIO],
	  CONVERT(VARCHAR(100), ACESSORIO_DS_DESCRICAO) [ACESSORIO_DS_DESCRICAO]
	FROM
	  ACESSORIO
  ) AS TB_ACESSORIO
UNPIVOT ([VALORES] FOR [COLUNAS] IN ([ACESSORIO_TP_ACESSORIO], [ACESSORIO_DS_DESCRICAO])) AS TB_PIVOT