USE ESTUDOS
GO

-- NULLS EM CONVERSÕES PARA PIVOT

-- PODE SER FEITO UM TRATAMENTO USANDO ISNULL OU COALESCE NOS CAMPOS QUE PODERÃO VIR NULL
-- O EXEMPLO ABAIXO DEMONSTRA ISSO
-- UMA NOVIDA NESSE EXEMPLO É O DATA TYPE SQL_VARIANT QUE PERMITE QUE QUALQUER TIPO DE DADO SEJA PASSADO PARA ELE.

DECLARE @TB_PESSOAS TABLE (
  ID_PESSOA NUMERIC(18,0) NOT NULL,
  CARACTERISTICA_PESSOA VARCHAR(100) NOT NULL,
  VALOR_CARACTERISTICA SQL_VARIANT NULL,
  PRIMARY KEY (ID_PESSOA, CARACTERISTICA_PESSOA)
)

INSERT INTO @TB_PESSOAS VALUES (1, 'Primeiro Nome', 'Gustavo')
INSERT INTO @TB_PESSOAS VALUES (1, 'Cidade onde mora', 'Almirante Tamandaré')
INSERT INTO @TB_PESSOAS VALUES (1, 'Primeiro nome da mãe', 'Lourdes')
INSERT INTO @TB_PESSOAS VALUES (2, 'Idade', 21)
INSERT INTO @TB_PESSOAS VALUES (2, 'Estado', 'PR')
INSERT INTO @TB_PESSOAS VALUES (3, 'Primeiro nome da mãe', 'Maria')
INSERT INTO @TB_PESSOAS VALUES (3, 'Idade', 55)
INSERT INTO @TB_PESSOAS VALUES (3, 'Estado', 'SP')

SELECT 
  ISNULL([Primeiro nome], 'NOME NÃO PREENCHIDO'), 
  ISNULL([Cidade onde mora], 'CIDADE NÃO PREENCHIDA'), 
  ISNULL([Primeiro nome da mãe], 'NOME DA MÃE NÃO PREENCHIDO'), 
  ISNULL([Idade], 0), 
  ISNULL([Estado], 'ESTADO NÃO PREENCHIDO')
FROM
  @TB_PESSOAS
PIVOT (MAX(VALOR_CARACTERISTICA) FOR CARACTERISTICA_PESSOA IN ([Primeiro nome], [Cidade onde mora], [Primeiro nome da mãe], [Idade], [Estado])) AS TB_PIVOT