USE ESTUDOS
GO

SET NOCOUNT ON

-- OUTPUT DEVE SER COLOCADO APÓS OS VALORES QUE SERÃO ATUALIZADOS SET X = 1 OUTPUT ...
-- DEVE SER USADO UMA ESPÉCIE DE ACESSO A UM MÉTODO
-- DELETED.NOMECAMPO OU INSERTED.NOMECAMPO PARA CAPTURAR OS VALORES DELETADOS OU INSERIDOS.
UPDATE 
  CARRO
SET 
  CARRO_NR_ANO = 2020 OUTPUT DELETED.CARRO_NR_ANO, INSERTED.CARRO_NR_ANO
WHERE 
  CARRO_NR_ID = 2