-- FUNÇÕES AGREGADAS
-- SÃO FUNÇÕES QUE REALIZAM A JUNÇÃO DE VALORES (AGREGAM)
-- SÃO ELAS: SUM, COUNT, MIN, MAX E AVG
USE ESTUDOS
GO

-- TRAZER O VALOR TOTAL DA VIPE DE CADA UM DOS VEÍCULOS E SUA RESPECTIVA QUANTIDADE
SELECT SUM(CARRO_VL_FIPE), CARRO_DS_MODELO, COUNT(*) FROM CARRO GROUP BY CARRO_DS_MODELO

-- O AVG AGREGOU TODOS OS VALORES DOS VEICULOS E CAPTUROU A MÉDIA DO VALOR DAS FIPES
SELECT AVG(CARRO_VL_FIPE) FROM CARRO

-- TROUXE O VALOR TOTAL DOS VEÍCULOS E EM OUTRA COLUNA, A SUA QUANTIDADE TOTAL
SELECT SUM(CARRO_VL_FIPE), COUNT(*) FROM CARRO
