-- FUNÇÕES ARITMÉTICAS
-- NÃO HÁ MUITO SEGREDO AQUI: + - * / %

USE ESTUDOS
GO

-- EXEMPLO 1 :
-- RETORNA O VALOR E PERCENTUAL DO DESCONTO DE CADA VEÍCULO ACRESCIDO DA COMISSÃO BASE DO VENDEDOR (1% VLR VEÍCULO) E O VALOR FINAL DO VEÍCULO
DECLARE 
  @PC_CMVENDEDOR NUMERIC(5,2)

SELECT 
  @PC_CMVENDEDOR = 1.00

SELECT 
  CARRO_NR_ID [ID VEICULO],
  CARRO_VL_FIPE [VALOR DO VEICULO],
  CARRO_PC_DSCAVISTA [PORCENTAGEM DESCONTO A VISTA],
  CARRO_VL_FIPE * (CARRO_PC_DSCAVISTA / 100) [VALOR DO DESCONTO A VISTA],
  @PC_CMVENDEDOR [PERCENTUAL COMISSÃO VENDEDOR],
  CARRO_VL_FIPE * (@PC_CMVENDEDOR / 100) [VALOR DA COMISSÃO VENDEDOR],
  CARRO_VL_FIPE - (CARRO_VL_FIPE * (CARRO_PC_DSCAVISTA / 100)) + (CARRO_VL_FIPE * (@PC_CMVENDEDOR / 100)) [VALOR FINAL VEICULO]
FROM
  CARRO

-- EXEMPLO 2:
-- SABER SE UM NÚMERO É PAR OU IMPAR OPERADOR MOD (%)
SELECT 
  CASE 
    WHEN CARRO_VL_FIPE % 2 = 0 THEN 'PAR' 
	ELSE 'IMPAR' 
  END
FROM CARRO