-- FUNÇÕES NÃO DETERMINISTICAS
-- AS FUNÇÕES NÃO DETERMINISTICAS PODEM RETORNAR VALORES DIFERENTES MESMO QUE O ESTADO DE BANCO DE DADOS SEJA IGUAL E QUE OS PARÂMETROS INFORMADOS SEJAM IGUAIS.

USE ESTUDOS
GO

-- EXEMPLO 1: 
SELECT GETDATE()
-- INDEPENDENTEMENTE DE QUANTAS VEZES OU A QUE MOMENTO EU EXECUTE O COMANDO ACIMA, ELE SEMPRE ME TORNARÁ UM VALOR DIFERENTE.
-- O ESTADO DO BANCO DE DADOS PODE PERMANECER O MESMO E OS PARÂMETROS INFORMADOS SÃO OS MESMOS (NENHUM), CONTUDO AINDA SIM O RETORNO É DIFERENTE.

-- A FUNÇÃO CONVERT DEPENDENDO DO PARÂMETRO INFORMADO, PODE NÃO SER DETERMINÍSTICA
-- PARA TAL COISA ACONTECER, O PARÂMETRO INFORMADO PARA A CONVERSÃO DEVE SER NÃO DETERMINISTICO.W
SELECT CONVERT(VARCHAR(200), GETDATE(), 103)
-- SE A CONSULTAR FOR EXECUTADA TODO DIA, DA MESMA MANEIRA ELA SEMPRE RETORNARÁ UM VALOR DIFERENTE DO ANTERIOR.

-- EXEMPLO 2:
-- O USO DA FUNÇÃO RAND() SEM O PARÂMETRO INFORMADO (SEED) GERA UM NÚMERO FLOAT TOTALMENTE RANDOMICO. SENDO A FUNÇÃO CONSIDERADA COMO NÃO DETERMINISTA.
-- CONTUDO AO UTILIZAR QUALQUER VALOR SENDO O SEED, ELA SE TORNA UMA FUNÇÃO DETERMINÍSTICA (POIS O SEED FOI INFORMADO)
-- * SE QUALQUER UM PARÂMETRO FOR INFORMADO PARA QUALQUER CHAMADA DO RAND, TODOS SE TORNARÃO DETERMINÍTAS (VÃO RETORNAR O MESMO VALOR SEMPRE)
SELECT RAND()
-- SELECT RAND(100)