USE ESTUDOS
GO

-- GROUP BY CUBE
-- BASICAMENTE O CUBE REALIZA O AGRUPAMENTO POR TODOS OS TIPOS DE AGRUPAMENTO QUE FOREM POSSÍVEIS COM OS PARÂMETROS INFORMADOS
-- ELE TAMBÉM REALIZA O AGRUPAMENTO SEM PARÂMETROS PARA OBTER O VALOR TOTAL
-- NÃO TEM MUITO SEGREDO, VOCÊ PASSA OS PARÂMETROS PRA ELE, E ELE GERA TODAS AS COMBINAÇÕES POSSÍVEIS DE AGRUPAMENTO PARA COM OS PARÂMETROS INFORMADOS.

SELECT 
  CARRO_TP_ACESSORIO,
  CARRO_PC_DSCAVISTA,
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
GROUP BY CUBE(CARRO_TP_ACESSORIO,
  CARRO_PC_DSCAVISTA)
  ORDER BY 1,2 DESC