USE ESTUDOS
GO

-- GROUPING SETS
-- DE QUALQUER MANEIRA A CLAUSULA GROUP BY PRECISA SER DECLARADA
-- A FUNÇÃO DEVOLVE O RESULTSET COM MULTIPLOS GROUP BY.
-- BASICAMENTE O GROUPING SETS, GERA O RESULTSET COM N TIPOS DE AGRUPAMENTO
-- CASO A QUESTÃO PEÇA PARA DEVOLVER UM RESULTSET AGRUPADO DE N MANEIRAS, UTILIZAR O GROUPING SETS


-- EXEMPLO : 1
-- TRAZER DE MANEIRA AGRUPADA E EM APENAS 1 RESULT SET AS SEGUINTES INFORMAÇÕES:
-- O TIPO DE ACESSÓRIO, COM O PERCENTUAL DE DESCONTO, O VALOR TOTAL DESSES E SUA MÉDIA AGRUPANDO POR TIPO DE ACESSÓRIO
-- O TIPO DE ACESSÓRIO, COM O PERCENTUAL DE DESCONTO, O VALOR TOTAL DESSES E SUA MÉDIA AGRUPANDO PELO PERCENTUAL DE DESCONTO
-- O TIPO DE ACESSÓRIO, COM O PERCENTUAL DE DESCONTO, O VALOR TOTAL DESSES E SUA MÉDIA AGRUPANDO POR TIPO DE ACESSÓRIO E PERCENTUAL DE DESCONTO
-- O TIPO DE ACESSÓRIO, COM O PERCENTUAL DE DESCONTO, O VALOR TOTAL DESSES E SUA MÉDIA SEM AGRUPAMENTO
SELECT 
  CARRO_TP_ACESSORIO,
  CARRO_PC_DSCAVISTA,
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
GROUP BY GROUPING SETS (
  (CARRO_TP_ACESSORIO),
  (CARRO_PC_DSCAVISTA),
  (CARRO_TP_ACESSORIO, CARRO_PC_DSCAVISTA),
  ()
) ORDER BY 1,2 DESC

-- SEM O GROUPING SETS, AS SOLICITAÇÕES PEDIDAS NO EXEMPLO 1 TERIAM QUE SER ATENDIDAS SEPARADAMENTE OU USANDO OS UNION ALLS PARA REALIZAR A JUNÇÃO DOS VALORES.
-- EXEMPLO SEM O USO DO GROUPING SETS

SELECT
  CARRO_TP_ACESSORIO [CARRO_TP_ACESSORIO],
  NULL [CARRO_PC_DSCAVISTA],
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
GROUP BY 
  CARRO_TP_ACESSORIO
UNION ALL
SELECT
  NULL [CARRO_TP_ACESSORIO],
  CARRO_PC_DSCAVISTA [CARRO_PC_DSCAVISTA],
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
GROUP BY 
  CARRO_PC_DSCAVISTA
UNION ALL
SELECT
  CARRO_TP_ACESSORIO [CARRO_TP_ACESSORIO],
  CARRO_PC_DSCAVISTA [CARRO_PC_DSCAVISTA],
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
GROUP BY
  CARRO_TP_ACESSORIO,
  CARRO_PC_DSCAVISTA
UNION ALL
SELECT
  NULL [CARRO_TP_ACESSORIO],
  NULL [CARRO_PC_DSCAVISTA],
  SUM(CARRO_VL_FIPE) [VALOR SEGMENTADO],
  AVG(CARRO_VL_FIPE) [MÉDIA SEGMENTADA]
FROM
  CARRO
ORDER BY 1,2 DESC


-- SEM UTILIZAR O GROUPING SETS, A CONSULTA FICA EXTREMAMENTE GRANDE! O QUE DIFICULDADE A SUA MANUTENÇÃO.