USE ESTUDOS
GO

-- CTE (COMMON TABLE EXPRESSIONS)
-- A CTE É UM RECURSO BEM IMPORTANTE E PRÁTICO.
-- BASICAMENTE ELA CONSEGUE REALIZAR SUBQUERYS E SE PARECE COM UMA TABELA DERIVADA
-- CONTUDO NO QUE ELA DIFERENCIA É A FLEXIBILIDADE E A POSSIBILIDADE DE SER CHAMADA NO CÓDIGO DIVERSAS VEZES COMO SE FOSSE UMA TABELA FÍSICA!
-- CONSEGUIMOS REALIZAR AQUI, UMA ESPÉCIE DE VIEW, POIS PODEMOS MANIPULAR E UNIR DIVERSAS TABELAS DENTRO DE APENAS UMA CTE, PROPORCIONANDO 1 ÚNICO RESULTSET
-- COM INFORMAÇÕES AGREGADAS DE OUTRAS TABELAS;

-- É POSSÍVEL USAR O CTE COMO FROM, BASE PARA INSERT, UPDATE OU DELETE, JOIN, CROSS OU OUTER APPLY.

-- SCHEMA BÁSICO DO CTE:
/*
WITH NOME_CTE(ALIAS_CAMPOS_OPCIONAL) AS (
SELECT
  CAMPO1,
  CAMPO2
FROM
  TABELA 
WHERE
  X = X
)

SELECT * FROM NOME_CTE

*/
-- EXEMPLO 1 : TRAZER TODAS AS VENDAS E OS RESPECTIVOS NOMES DE CADA UM DIS COMPRADORES.
WITH VENDAS_E_CLIENTES AS (
SELECT
  VENDA_VL_TOTAL,
  CLIENTE_NM_NOME
FROM
  VENDA INNER JOIN CLIENTE ON (VENDA_NR_CLIENTE = CLIENTE_NR_ID)
)
SELECT * FROM VENDAS_E_CLIENTES

-- A DIFERENÇA ENTRE UMA TABELA TEMPORÁRIA
-- O CTE PODE SER USADO SOMENTE NO MOMENTO DE EXECUÇÃO DA ROTINA, ENQUANTO A TABELA TEMPORÁRIA FICA DISPONÍVEL A TODOS INSTANTE DA SESSÃO.
-- O CTE AUTOMATICAMENTE CRIA OS CAMPOS COM OS MESMOS DATATYPES DOS CAMPOS ORIGINAIS, ENQUANTO NAS TABELAS TEMPORÁRIAS VOCÊ DEVERIA INSERIR MANUALMENTE.
-- CTE É MAIS PERFORMÁTICO ALÉM DE PERMITIR RECURSIVIDADE, FUNCIONANDO COMO UMA ESPÉCIE DE FUNÇÃO!