USE ESTUDOS
GO

-- USO DE EXPRESSÕES RECURSIVAS COM CTE

-- NESSE CASO, O CTE FOI CHAMADO POR ELE MESMO, REALIZANDO O RETORNO DO NUMERO E INCREMENTANDO MAIS UM.
-- UM PARÂMETRO ADICIONAL FOI INCLUSO APÓS A REFERÊNCIA NO FROM. OPTION(MAXRECURSION XXXX) DEFINE A QUANTIDADE MÁXIMA DO GRAU DE RECURSIVIDADE DA CTE
-- EVITANDO QUE A MEMÓRIA ESTOURE.
-- CADA CTE OBRIGATÓRIAMENTE PRECISA TERMINAR COM O PONTO E VIRGULA!

-- EXEMPLO 1 : USANDO A RECURSIVIDADE, SOMAR 1 + O ÚLTIMO NÚMERO ATÉ 10.
WITH CTE_RECURSIVO AS (
  SELECT 1 NUMERO
  UNION ALL
  SELECT NUMERO+1 NUMERO FROM CTE_RECURSIVO WHERE NUMERO <= 10
) 
SELECT * FROM CTE_RECURSIVO OPTION(MAXRECURSION 10);

-- EXEMPLO 2 : IMPRIMIR TODAS AS DATAS QUE ESTÃO ENTRE O DIA DE HOJE ATÉ O DIA 30 DO 11 DE 2021.
WITH CTE_DATAS_ATE_ANIVERSARIO AS (
  SELECT CONVERT(DATE, GETDATE()) DATAS_ATE_ANIVERSARIO
  UNION ALL
  SELECT DATEADD(DD, +1, DATAS_ATE_ANIVERSARIO) FROM CTE_DATAS_ATE_ANIVERSARIO WHERE CONVERT(VARCHAR(8), DATAS_ATE_ANIVERSARIO, 112) <= '20211130'
)

SELECT * FROM CTE_DATAS_ATE_ANIVERSARIO OPTION(MAXRECURSION 1000)